Repository milieuinfo/webcomponent-vl-ui-typography, pull requests merged in 2020-01, with the labels that each got.

#7 Niuewe test opzet
  .mocharc.js
  README.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  index.js
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
  test/e2e/components/vl-typography.js
  test/e2e/pages/vl-typography.page.js
  test/e2e/typography.test.js
  test/unit/vl-typography.test.html
  test/wct.docker.conf.json
  vl-typography.src.js
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore

#8 Upgrade uglifyjs om disceprantie met @govflanders/vl-ui-util te fixen
  package-lock.json
  package.json
  vl-typography.js
Labels: chore

#9 Verwijder overbodige dependencies
  package-lock.json
  package.json
Labels: chore

#10 Update package-lock
  package-lock.json
  vl-typography.js
Labels: chore

#11 Fix typo
  package.json
Labels: chore

#12 VOORTOETS-3050
  demo/demo.css
  demo/demo.css.map
  demo/vl-typography.html
  package-lock.json
  package.json
  style.css
  style.css.map
  test/e2e/components/vl-typography.js
  test/e2e/pages/vl-typography.page.js
  test/e2e/typography.test.js
Labels: enhancement

#13 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#15 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#14 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#16 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#17 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
