Repository milieuinfo/webcomponent-vl-ui-typography, pull requests merged in 2020-06, with the labels that each got.

#35 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-typography.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-typography.js
  test/e2e/components/vl-typography.js
  test/e2e/pages/vl-typography.page.js
  test/e2e/typography.test.js
  test/unit/vl-typography.test.html
Labels: chore

#36 Verander de controle op het renderen van de p- en a-tag
  package-lock.json
  test/e2e/typography.test.js
Labels: bugfix

#39 Introductie nieuw Vlaanderen icon fontdependencies update
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
Labels: bug

#41 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
